# Generated by Django 4.0.8 on 2022-11-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='variations',
        ),
    ]
