# Generated by Django 4.0.8 on 2022-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('cart', '0003_remove_cartitems_variations_cartitems_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
