# Generated by Django 4.0.8 on 2022-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
