# Generated by Django 4.0.8 on 2022-11-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_order_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(max_length=100),
        ),
    ]
