# Generated by Django 4.0.8 on 2022-11-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='book_format',
        ),
    ]
